version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      # Install dependencies needed for running tests
      - echo Installing dependencies

  build:
    commands:
      - echo Build started on `date`
      - echo Running tests
        # - python3 manage.py runserver

  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'
